# AI Module
EasyBasket.country=India
EasyBasket.isActive=true
EasyBasket.listOfValues=val1,val2,val3

# Payment Module
EasyBasket.merchantId=MERCHANT_001
EasyBasket.isPaymentActive=true
EasyBasket.supportedUpiApps=GPay,PhonePe,Paytm
